CXX = clang++
CXXFLAGS = -std=c++11 -lcrypto 

chal1:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_1.cpp 

chal2:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_2.cpp 

chal3:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_3.cpp 

chal4:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_4.cpp 

chal5:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_5.cpp

chal6:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_6.cpp 

chal7:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_7.cpp 

chal8:
	$(CXX) $(CXXFLAGS) baseClasses.cpp c_8.cpp 

clean:
	rm *.out *output*.txt